### ISSUE TITLE
SW Issues

### ISSUE THREAD

**Issue by yuriploc** [ChemicalRocketeer/funfunmentorship#6]
Hi there,

Just saw the topic in FFForum and got an error with the Service Workers.

![image](https://user-images.githubusercontent.com/2575359/34073229-c716f3e4-e273-11e7-84cc-b3f079892277.png)

As I (still) don't have any experience with SW, I can't submit a PR right now. But I'll try, if anybody else doesn't (:

**Comment by blatayue** [comment]
Has to do with the rate limiting imposed by discourse. The network error is the equivalent of mpj's Heroku application error. The issues been brought up [here](https://www.funfunforum.com/t/show-us-where-you-are-fff-user-map/1659/117) with his response 3 posts down [here.](https://www.funfunforum.com/t/show-us-where-you-are-fff-user-map/1659/120)
